// Fractalize Studio's curated photo catalog -- a static snapshot of
// tuckermills.com's own photo galleries, generated by hand from
// GALLERIES in tuckermills-portfolio/gallery.js, with every src/thumbSrc
// made absolute (this site is a different origin/repo, so it can't use
// tuckermills.com's own relative paths). A deliberate, explicit snapshot
// rather than a live fetch against tuckermills.com at page load -- same
// "sync on purpose, don't couple live" choice already made for the
// fractalize-core git submodule itself.
//
// To regenerate: copy GALLERIES/GALLERY_LABELS from
// tuckermills-portfolio/gallery.js, prefix every folder with
// "https://www.tuckermills.com/", and skip any filename listed in that
// collection's own `portfolioPrivate` array (none exist as of this
// snapshot -- every photo below is public on tuckermills.com too).
window.FRACTALIZE_CATALOG = (function () {
  const TUCKERMILLS_ORIGIN = "https://www.tuckermills.com/";
  const GALLERIES = [
    {
      label: "Macro",
      folder: "Images/Photography/Collections/macro/",
      images: [
        "macro-01.jpg",
        "macro-02.jpg",
        "macro-03.jpg",
        "macro-04.jpg",
        "macro-05.jpg",
        "macro-06.jpg",
        "macro-07.jpg",
        "macro-08.jpg",
        "macro-09.jpg",
        "macro-10.jpg",
        "IMG_20180721_162815.jpg",
      ],
    },
    {
      label: "China",
      folder: "Images/Photography/Collections/china-bw/",
      images: [
        "nav-image-1.jpg",
        "1.jpg",
        "2.jpg",
        "5.jpg",
        "6.jpg",
        "8.jpg",
        "8 (2).jpg",
        "8 (3).jpg",
        "9.jpg",
        "12.jpg",
        "21.jpg",
        "23.jpg",
      ],
    },
    {
      label: "China Travels",
      folder: "Images/Photography/Collections/china-travels-bw/",
      images: [
        "banner-3.jpg",
        "000022.jpg",
        "000024.jpg",
        "000025.jpg",
        "000032.jpg",
        "000042.jpg",
        "000043.jpg",
        "000046.jpg",
      ],
    },
    {
      label: "Travels in Color",
      folder: "Images/Photography/Collections/color-travels/",
      images: ["banner-2.jpg", "000293960002.jpg", "000293960030.jpg", "000294510012.jpg"],
    },
  ];

  return GALLERIES.map((group) => ({
    label: group.label,
    photos: group.images.map((filename) => ({
      src: TUCKERMILLS_ORIGIN + group.folder + filename,
      thumbSrc: TUCKERMILLS_ORIGIN + group.folder + "thumbs/" + filename,
    })),
  }));
})();
