// Fractalize Studio's curated photo catalog -- a static snapshot of
// tuckermills.com's own photo galleries, generated by hand from
// GALLERIES in tuckermills-portfolio/gallery.js, with every src/thumbSrc
// made absolute (this site is a different origin/repo, so it can't use
// tuckermills.com's own relative paths). A deliberate, explicit snapshot
// rather than a live fetch against tuckermills.com at page load -- same
// "sync on purpose, don't couple live" choice already made for the
// fractalize-core git submodule itself.
//
// To regenerate: copy GALLERIES/GALLERY_LABELS from
// tuckermills-portfolio/gallery.js, prefix every folder with
// "https://www.tuckermills.com/", and skip any filename listed in that
// collection's own `portfolioPrivate` array (none exist as of this
// snapshot -- every photo below is public on tuckermills.com too).
// Last regenerated from tuckermills-portfolio commit 5b82101 (adds the
// Colors & Lights collection and new photos across four others).
window.FRACTALIZE_CATALOG = (function () {
  const TUCKERMILLS_ORIGIN = "https://www.tuckermills.com/";
  const GALLERIES = [
    {
      label: "Macro",
      folder: "Images/Photography/Collections/macro/",
      images: [
        "macro-01.jpg",
        "macro-02.jpg",
        "macro-03.jpg",
        "macro-04.jpg",
        "macro-05.jpg",
        "macro-06.jpg",
        "macro-07.jpg",
        "macro-08.jpg",
        "macro-09.jpg",
        "macro-10.jpg",
        "IMG_20180721_162815.jpg",
        "000538810019.jpg",
        "000538810034.jpg",
        "000849230010.jpg",
        "000849240033.jpg",
        "000849260001.jpg",
        "000849260002.jpg",
        "000849260017.jpg",
      ],
    },
    {
      label: "China",
      folder: "Images/Photography/Collections/china-bw/",
      images: [
        "nav-image-1.jpg",
        "1.jpg",
        "2.jpg",
        "5.jpg",
        "6.jpg",
        "8.jpg",
        "8 (2).jpg",
        "8 (3).jpg",
        "9.jpg",
        "12.jpg",
        "21.jpg",
        "23.jpg",
        "img007.jpg",
        "img009-1.jpg",
        "img010.jpg",
        "img013.jpg",
        "img014.jpg",
        "img016.jpg",
        "img018-1.jpg",
        "img018-2.jpg",
        "img019-1.jpg",
        "img019-2.jpg",
        "img020.jpg",
        "img022.jpg",
        "img023.jpg",
        "img024.jpg",
        "img026.jpg",
        "img033.jpg",
      ],
    },
    {
      label: "China Travels",
      folder: "Images/Photography/Collections/china-travels-bw/",
      images: [
        "banner-3.jpg",
        "000022.jpg",
        "000024.jpg",
        "000025.jpg",
        "000032.jpg",
        "000042.jpg",
        "000043.jpg",
        "000046.jpg",
        "000056.jpg",
        "img007.jpg",
        "img022.jpg",
        "img023.jpg",
      ],
    },
    {
      label: "Travels in Color",
      folder: "Images/Photography/Collections/color-travels/",
      images: [
        "banner-2.jpg",
        "000293960002.jpg",
        "000293960030.jpg",
        "000294510012.jpg",
        "000538800009.jpg",
        "000538800015.jpg",
        "000849220005.jpg",
        "000849220009.jpg",
        "000849220026.jpg",
        "000849240018.jpg",
        "000849250020.jpg",
        "000849250021.jpg",
        "000849260012.jpg",
        "img015.jpg",
        "img018.jpg",
        "img026.jpg",
        "img027.jpg",
        "img063.jpg",
      ],
    },
    {
      label: "Colors & Lights",
      folder: "Images/Photography/Collections/Colors & Lights/",
      images: [
        "000483810015.jpg",
        "000483810017.jpg",
        "000483810020.jpg",
        "000483810028.jpg",
        "img011.jpg",
        "img012.jpg",
      ],
    },
    {
      label: "Unsorted",
      folder: "Images/Photography/Collections/unsorted/",
      images: [
        "000294300017.jpg",
        "000294300022.jpg",
        "000294300024.jpg",
        "000294300027.jpg",
        "000294300028.jpg",
        "000294350008.jpg",
        "000294350013.jpg",
        "000294420002.jpg",
        "000294420003.jpg",
        "000294420008.jpg",
        "000294420010.jpg",
        "000294420023.jpg",
        "000294420028.jpg",
        "000294470023.jpg",
        "000294470028.jpg",
        "000294510002.jpg",
        "000294510009.jpg",
        "000294530007.jpg",
        "000294530034.jpg",
        "000294560006.jpg",
        "000294560018.jpg",
        "000294560025.jpg",
        "000294570025.jpg",
        "img005.jpg",
        "img007.jpg",
        "img021.jpg",
        "img025.jpg",
        "img028.jpg",
        "img031.jpg",
        "img034.jpg",
        "img044.jpg",
        "img074.jpg",
        "img085.jpg",
        "img090.jpg",
        "img095.jpg",
        "img101.jpg",
        "img111.jpg",
        "img123.jpg",
        "img126.jpg",
        "img128.jpg",
        "img132.jpg",
      ],
    },
  ];

  return GALLERIES.map((group) => ({
    label: group.label,
    photos: group.images.map((filename) => ({
      src: TUCKERMILLS_ORIGIN + group.folder + filename,
      thumbSrc: TUCKERMILLS_ORIGIN + group.folder + "thumbs/" + filename,
    })),
  }));
})();
